### ISSUE TITLE
Issue when upgrading the shootemup to v0.25.0

### ISSUE THREAD

**Issue by eonarheim** [excaliburjs/Excalibur#2158]
### Proposal

Research alternative and/or additional distribution strategies to smooth over this experience 
* UMD bundle on separate export path?
* UMD bundle CDN hosted
* Angular approach with multiple module types in dist
* Other approaches to hint the bundler?
* Others?

@kamranayub has some good thoughts on this https://github.com/excaliburjs/Excalibur/discussions/2156#discussioncomment-1809721

### Steps to Reproduce

Upgrading the shootemup to v0.25.0 yields a confusing error in the console.

`webpack error Uncaught TypeError: __webpack_require__.r is not a function`

### Expected Result

Ideally this experience with webpack (and other bundlers) should be smoother for people not familiar with them.

### Actual Result

Confusing errors, need to 

### Environment

- browsers and versions: NA
- operating system: NA
- Excalibur versions: v0.25.0

### Current Workaround

Reference the webpack template (or other bundler templates) https://github.com/excaliburjs/template-ts-webpack

**Comment by eonarheim** [comment]
Shootemup is upgraded to latest excalibur
